// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Entities;

namespace Web.Entities.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190710130344_DinamickaPravaProjekat")]
    partial class DinamickaPravaProjekat
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web.Entities.Models.Base.Dokument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<int?>("KomentarId");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Naziv");

                    b.Property<string>("Putanja");

                    b.HasKey("Id");

                    b.HasIndex("KomentarId");

                    b.ToTable("Dokumenti");
                });

            modelBuilder.Entity("Web.Entities.Models.Base.Komentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Tekst")
                        .HasMaxLength(200);

                    b.Property<int>("ZahtjevId");

                    b.HasKey("Id");

                    b.HasIndex("ZahtjevId");

                    b.ToTable("Komentari");
                });

            modelBuilder.Entity("Web.Entities.Models.Base.LogAkcija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Akcija");

                    b.Property<DateTime>("DatumAkcije");

                    b.Property<int>("Kategorija");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(64);

                    b.Property<int>("Level");

                    b.Property<string>("Opis");

                    b.HasKey("Id");

                    b.HasIndex("KorisnickoIme");

                    b.ToTable("LogAkcije");
                });

            modelBuilder.Entity("Web.Entities.Models.Base.LogEntitet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumAkcije");

                    b.Property<int>("Entitet");

                    b.Property<int>("EntitetId");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(64);

                    b.Property<string>("Vrijednost");

                    b.HasKey("Id");

                    b.HasIndex("KorisnickoIme");

                    b.ToTable("LogEntiteti");
                });

            modelBuilder.Entity("Web.Entities.Models.Base.Postavke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AutorskaPravaKarte")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("NaslovSistema")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("TrajanjeSesije");

                    b.Property<string>("UrlKarte")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Postavke");
                });

            modelBuilder.Entity("Web.Entities.Models.Base.Projekat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Naziv");

                    b.Property<string>("Opis");

                    b.HasKey("Id");

                    b.ToTable("Projekti");
                });

            modelBuilder.Entity("Web.Entities.Models.Base.Zahtjev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Naziv");

                    b.Property<string>("Opis");

                    b.Property<int>("ProjekatId");

                    b.HasKey("Id");

                    b.HasIndex("ProjekatId");

                    b.ToTable("Zahtjevi");
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.Korisnik", b =>
                {
                    b.Property<string>("KorisnickoIme")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<string>("BrojMobitela");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<bool>("EmailVerifikovan");

                    b.Property<int?>("Jezik");

                    b.Property<string>("ModifiedBy");

                    b.Property<bool>("Onemogucen");

                    b.Property<int?>("PolId");

                    b.Property<string>("PunoIme")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<byte[]>("Tajna");

                    b.Property<int>("UlogaDisc");

                    b.HasKey("KorisnickoIme");

                    b.HasIndex("KorisnickoIme")
                        .IsUnique();

                    b.HasIndex("PolId");

                    b.HasIndex("UlogaDisc");

                    b.ToTable("Korisnici");

                    b.HasDiscriminator<int>("UlogaDisc").HasValue(0);
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.KorisnikUloga", b =>
                {
                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(64);

                    b.Property<int>("UlogaId");

                    b.HasKey("KorisnickoIme", "UlogaId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisnikUloge");
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.Modul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Naziv")
                        .HasMaxLength(200);

                    b.Property<string>("Opis")
                        .HasMaxLength(200);

                    b.Property<string>("Sifra")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.HasIndex("Sifra")
                        .IsUnique()
                        .HasFilter("[Sifra] IS NOT NULL");

                    b.ToTable("Moduli");
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.PravoAkcija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Naziv")
                        .HasMaxLength(200);

                    b.Property<string>("Opis")
                        .HasMaxLength(200);

                    b.Property<int>("PravoObjektId");

                    b.Property<string>("Sifra")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("PravoObjektId");

                    b.HasIndex("Sifra")
                        .IsUnique()
                        .HasFilter("[Sifra] IS NOT NULL");

                    b.ToTable("PravoAkcije");
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.PravoAkcijaUloga", b =>
                {
                    b.Property<int>("PravoAkcijaId");

                    b.Property<int>("UlogaId");

                    b.HasKey("PravoAkcijaId", "UlogaId");

                    b.HasIndex("UlogaId");

                    b.ToTable("PravoAkcijaUloge");
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.PravoGrupa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Naziv")
                        .HasMaxLength(200);

                    b.Property<string>("Opis")
                        .HasMaxLength(200);

                    b.Property<string>("Sifra")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.HasIndex("Sifra")
                        .IsUnique()
                        .HasFilter("[Sifra] IS NOT NULL");

                    b.ToTable("PravoGrupe");
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.PravoObjekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("ModulId");

                    b.Property<string>("Naziv")
                        .HasMaxLength(200);

                    b.Property<int>("PravoGrupaId");

                    b.Property<string>("Sifra")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.HasIndex("ModulId");

                    b.HasIndex("PravoGrupaId");

                    b.HasIndex("Sifra")
                        .IsUnique()
                        .HasFilter("[Sifra] IS NOT NULL");

                    b.ToTable("PravoObjekti");
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.PravoUpravljanjaKorisnikom", b =>
                {
                    b.Property<int>("UlogaUpraviteljaId");

                    b.Property<int>("UlogaUpravljanogId");

                    b.HasKey("UlogaUpraviteljaId", "UlogaUpravljanogId");

                    b.HasIndex("UlogaUpravljanogId");

                    b.ToTable("PravaUpravljanjaKorisnicima");
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DatumIsteka");

                    b.Property<DateTime>("DatumKreiranja");

                    b.Property<DateTime>("DatumPosljednjeAkcije");

                    b.Property<string>("PosljednjiIp")
                        .HasMaxLength(256);

                    b.Property<string>("PosljednjiKlijent")
                        .HasMaxLength(256);

                    b.Property<int>("Tip");

                    b.Property<int>("UlogaId");

                    b.Property<string>("VlasnikKorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("UlogaId");

                    b.HasIndex("VlasnikKorisnickoIme");

                    b.ToTable("Tokeni");
                });

            modelBuilder.Entity("Web.Entities.Models.Sifarnik.FrontendModul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Naziv");

                    b.Property<bool>("Onemogucen");

                    b.Property<string>("Sifra");

                    b.HasKey("Id");

                    b.ToTable("FrontendModuli");
                });

            modelBuilder.Entity("Web.Entities.Models.Sifarnik.LogKategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("Poredak");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("VrijednostUAplikaciji");

                    b.HasKey("Id");

                    b.ToTable("LogKategorije");
                });

            modelBuilder.Entity("Web.Entities.Models.Sifarnik.LogLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("Poredak");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("VrijednostUAplikaciji");

                    b.HasKey("Id");

                    b.ToTable("LogLeveli");
                });

            modelBuilder.Entity("Web.Entities.Models.Sifarnik.Pol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("Poredak");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("VrijednostUAplikaciji");

                    b.HasKey("Id");

                    b.ToTable("Polovi");
                });

            modelBuilder.Entity("Web.Entities.Models.Sifarnik.Prevod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Jezik");

                    b.Property<string>("ModifiedBy");

                    b.Property<string>("Polje");

                    b.Property<string>("PrevodTekst");

                    b.Property<int>("RedId");

                    b.Property<string>("Tabela");

                    b.HasKey("Id");

                    b.ToTable("Prevodi");
                });

            modelBuilder.Entity("Web.Entities.Models.Sifarnik.Uloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<int>("FrontendModulId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("Poredak");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("VrijednostUAplikaciji");

                    b.HasKey("Id");

                    b.HasIndex("FrontendModulId");

                    b.ToTable("Uloge");
                });

            modelBuilder.Entity("Web.Entities.Models.Sifarnik.VrstaLogAkcija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumIzmjene");

                    b.Property<DateTime?>("DatumKreiranja");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("Poredak");

                    b.Property<string>("Sifra")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("VrijednostUAplikaciji");

                    b.HasKey("Id");

                    b.ToTable("VrsteLogAkcija");
                });

            modelBuilder.Entity("Web.Entities.Models.Base.Dokument", b =>
                {
                    b.HasOne("Web.Entities.Models.Base.Komentar")
                        .WithMany("Dokumenti")
                        .HasForeignKey("KomentarId");
                });

            modelBuilder.Entity("Web.Entities.Models.Base.Komentar", b =>
                {
                    b.HasOne("Web.Entities.Models.Base.Zahtjev", "Zahtjev")
                        .WithMany("Komentari")
                        .HasForeignKey("ZahtjevId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Entities.Models.Base.LogAkcija", b =>
                {
                    b.HasOne("Web.Entities.Models.Korisnik.Korisnik", "Korisnik")
                        .WithMany("LogAkcije")
                        .HasForeignKey("KorisnickoIme");
                });

            modelBuilder.Entity("Web.Entities.Models.Base.LogEntitet", b =>
                {
                    b.HasOne("Web.Entities.Models.Korisnik.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnickoIme");
                });

            modelBuilder.Entity("Web.Entities.Models.Base.Zahtjev", b =>
                {
                    b.HasOne("Web.Entities.Models.Base.Projekat", "Projekat")
                        .WithMany("Zahtjevi")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.Korisnik", b =>
                {
                    b.HasOne("Web.Entities.Models.Sifarnik.Pol", "Pol")
                        .WithMany()
                        .HasForeignKey("PolId");
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.KorisnikUloga", b =>
                {
                    b.HasOne("Web.Entities.Models.Korisnik.Korisnik", "Korisnik")
                        .WithMany("KorisnikUloge")
                        .HasForeignKey("KorisnickoIme")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Web.Entities.Models.Sifarnik.Uloga", "Uloga")
                        .WithMany("KorisnikUloge")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.PravoAkcija", b =>
                {
                    b.HasOne("Web.Entities.Models.Korisnik.PravoObjekt", "PravoObjekt")
                        .WithMany("PravoAkcije")
                        .HasForeignKey("PravoObjektId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.PravoAkcijaUloga", b =>
                {
                    b.HasOne("Web.Entities.Models.Korisnik.PravoAkcija", "PravoAkcija")
                        .WithMany("PravoAkcijaUloge")
                        .HasForeignKey("PravoAkcijaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Web.Entities.Models.Sifarnik.Uloga", "Uloga")
                        .WithMany("PravoAkcijaUloge")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.PravoObjekt", b =>
                {
                    b.HasOne("Web.Entities.Models.Korisnik.Modul", "Modul")
                        .WithMany("PravoObjekti")
                        .HasForeignKey("ModulId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Web.Entities.Models.Korisnik.PravoGrupa", "PravoGrupa")
                        .WithMany("PravoObjekti")
                        .HasForeignKey("PravoGrupaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.PravoUpravljanjaKorisnikom", b =>
                {
                    b.HasOne("Web.Entities.Models.Sifarnik.Uloga", "UlogaUpravitelja")
                        .WithMany("PravaUpravljanja")
                        .HasForeignKey("UlogaUpraviteljaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Web.Entities.Models.Sifarnik.Uloga", "UlogaUpravljanog")
                        .WithMany("PravaUpravljanosti")
                        .HasForeignKey("UlogaUpravljanogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Entities.Models.Korisnik.Token", b =>
                {
                    b.HasOne("Web.Entities.Models.Sifarnik.Uloga", "Uloga")
                        .WithMany("Tokeni")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Web.Entities.Models.Korisnik.Korisnik", "Vlasnik")
                        .WithMany()
                        .HasForeignKey("VlasnikKorisnickoIme")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Entities.Models.Sifarnik.Uloga", b =>
                {
                    b.HasOne("Web.Entities.Models.Sifarnik.FrontendModul", "FrontendModul")
                        .WithMany("Uloge")
                        .HasForeignKey("FrontendModulId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
